import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Inter_Tight } from "next/font/google";
import "./globals.css";
import Head from "next/head";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <Head>
        <link href="https://fonts.cdnfonts.com/css/gilroy-bold" rel="stylesheet"/>
    </Head>
    <body
        className={``}
    >
    {children}
    </body>
    </html>
  );
}
